In [1]:
import pandas as pd
import sqlite3 as sql

In [2]:
conn = sql.connect('database.sqlite')
conn

In [3]:
'select * from sqlite_master'

'select * from sqlite_master'

In [4]:
pd.read_sql_query('select * from sqlite_master',conn)

,type,name,tbl_name,rootpage,sql
0,table,Salaries,Salaries,2,CREATE TABLE Salaries (\n Id INTEGER PRIMAR...
1,index,salaries_year_idx,Salaries,16566,CREATE INDEX salaries_year_idx ON Salaries (Year)

In [5]:
pd.read_sql_query('select * from salaries',conn)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0,400184.25,,9999999.00,567595.43,2011,,San Francisco,
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,,335279.91,335279.91,2011,,San Francisco,
2,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916,56120.71,198306.9,,332343.61,332343.61,2011,,San Francisco,
3,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737,182234.59,,326373.19,326373.19,2011,,San Francisco,
4,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602,8601,189082.74,,316285.74,316285.74,2011,,San Francisco,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148648,148650,Roy I Tillery,Custodian,0,0,0,0,0.00,0.00,2014,,San Francisco,PT
148649,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148650,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148651,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,,San Francisco,
148652,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0,0,-618.13,0,-618.13,-618.13,2014,,San Francisco,PT

In [6]:
pd.read_sql_query("select employeename from salaries",conn)

             EmployeeName
0          NATHANIEL FORD
1          ALBERT PARDINI
2       CHRISTOPHER CHONG
3         PATRICK GARDNER
4          DAVID SULLIVAN
...                   ...
148648      Roy I Tillery
148649       Not provided
148650       Not provided
148651       Not provided
148652          Joe Lopez

[148653 rows x 1 columns]

#### **1. What is the average TotalPayBenefits for each JobTitle? exclude ('Not Provided', 'Not provided')**

In [12]:
query_1 = """
select
    JobTitle, 
    AVG(TotalPayBenefits) AS AverageTotalPayBenefits
FROM Salaries
WHERE JobTitle NOT IN ('Not Provided', 'Not provided')
GROUP BY JobTitle;
"""
df1 = pd.read_sql_query(query_1, conn)
df1

                                            JobTitle  AverageTotalPayBenefits
0                                      ACCOUNT CLERK             44035.664337
1                                         ACCOUNTANT             47429.268000
2                                  ACCOUNTANT INTERN             29031.742917
3                        ACPO,JuvP, Juv Prob (SFERS)             80266.370000
4                                      ACUPUNCTURIST             67594.400000
...                                              ...                      ...
2153                           X-RAY LABORATORY AIDE             52705.880385
2154                           X-Ray Laboratory Aide             69521.123200
2155  YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS             53632.870000
2156                              Youth Comm Advisor             60118.550000
2157                                     ZOO CURATOR             66686.560000

[2158 rows x 2 columns]

#### **2. Show The JobTitle and Overtime Pay for All Employees With Overtime Pay greater than 50000**

In [13]:
query_2 = """
SELECT 
    JobTitle, 
    OvertimePay
FROM Salaries
WHERE OvertimePay > 50000;
"""
df_2 = pd.read_sql_query(query_2, conn)
df_2

                                              JobTitle   OvertimePay
0                      CAPTAIN III (POLICE DEPARTMENT)     106088.18
1                 WIRE ROPE CABLE MAINTENANCE MECHANIC      56120.71
2                   BATTALION CHIEF, (FIRE DEPARTMENT)       89062.9
3                   BATTALION CHIEF, (FIRE DEPARTMENT)      86362.68
4     ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)      71344.88
...                                                ...           ...
2163                           Parking Control Officer      54738.36
2164                                      Not provided  Not Provided
2165                                      Not provided  Not Provided
2166                                      Not provided  Not Provided
2167                                      Not provided  Not Provided

[2168 rows x 2 columns]

#### **3. What is the total number of unique employees? exclude ('Not Provided', 'Not provided')**

In [9]:
query_3 = """
SELECT 
    COUNT(DISTINCT EmployeeName) AS TotalUniqueEmployees
FROM Salaries
WHERE EmployeeName NOT IN ('Not Provided', 'Not provided');
"""
df_3 = pd.read_sql_query(query_3, conn)
df_3

   TotalUniqueEmployees
0                110808

#### **4.Show The Top 10 highest Paid Employees**

In [10]:
query_4 = """
SELECT 
    EmployeeName, 
    JobTitle, 
    TotalPayBenefits
FROM Salaries
ORDER BY TotalPayBenefits DESC
LIMIT 10;
"""
df_4 = pd.read_sql_query(query_4, conn)
df_4

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
5,Joanne M Hayes-White,"Chief, Fire Department",422353.40
6,Gregory P Suhr,Chief of Police,418019.22
7,Joanne M Hayes-White,"Chief, Fire Department",417435.10
8,Ellen G Moffatt,Asst Med Examiner,415767.94
9,Gary Altenberg,"Lieutenant, Fire Suppression",407274.78

#### **5.Show All Employees Ordered By Their TotalPay Benefits In Descending Order**

In [11]:
query_5 = """
SELECT 
    EmployeeName, 
    JobTitle, 
    TotalPayBenefits
FROM Salaries
ORDER BY TotalPayBenefits DESC;
"""
df_5 = pd.read_sql_query(query_5, conn)
df_5

,EmployeeName,JobTitle,TotalPayBenefits
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,567595.43
1,David Shinn,Deputy Chief 3,510732.68
2,Amy P Hart,Asst Med Examiner,479652.21
3,William J Coaker Jr.,Chief Investment Officer,436224.36
4,Gregory P Suhr,Chief of Police,425815.28
...,...,...,...
148648,Not provided,Not provided,0.00
148649,Timothy E Gibson,Police Officer 3,-2.73
148650,Mark E Laherty,Police Officer 3,-8.20
148651,David P Kucia,Police Officer 3,-33.89
148652,Joe Lopez,"Counselor, Log Cabin Ranch",-618.13